services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - JELLYFIN_HttpPort=${JELLYFIN_HTTP_PORT}
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "${JELLYFIN_HTTP_PORT}:${JELLYFIN_HTTP_PORT}"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8888}
      - TORRENTING_PORT=${QBITTORRENT_TORRENTING_PORT:-6881}
    volumes:
      - qbittorrent_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "${QBITTORRENT_WEBUI_PORT:-8888}:${QBITTORRENT_WEBUI_PORT:-8888}"
      - "${QBITTORRENT_TORRENTING_PORT:-6881}:${QBITTORRENT_TORRENTING_PORT:-6881}"
      - "${QBITTORRENT_TORRENTING_PORT:-6881}:${QBITTORRENT_TORRENTING_PORT:-6881}/udp"
    networks:
      - media_network
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "${SONARR_PORT:-8989}:8989"
    networks:
      - media_network
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - radarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "${RADARR_PORT:-7878}:7878"
    networks:
      - media_network
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
    networks:
      - media_network
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    volumes:
      - bazarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "${BAZARR_PORT:-6767}:6767"
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:

volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  bazarr_config:
