services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8888
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "8888:8888"
      - "6881:6881"
      - "6881:6881/udp"
    networks:
      - media_network
      - i2p_network
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    volumes:
      - sonarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "8989:8989"
    networks:
      - media_network
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    volumes:
      - radarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "7878:7878"
    networks:
      - media_network
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    volumes:
      - prowlarr_config:/config
    ports:
      - "9696:9696"
    networks:
      - media_network
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    volumes:
      - bazarr_config:/config
      - ${MEDIA_FOLDER}:/data
    ports:
      - "6767:6767"
    networks:
      - media_network
    restart: unless-stopped

networks:
  media_network:
  i2p_network:
    external: true

volumes:
  jellyfin_config:
  qbittorrent_config:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  bazarr_config:
